type = "card"
title = "获奖"
description = "获得的荣誉与奖项。"

[[items]]
title = "国家奖学金"
subtitle = "中华人民共和国教育部"
date = "2025"
content = "奖励特别优秀学生的级别最高的国家级奖学金。"

[[items]]
title = "国家奖学金"
subtitle = "中华人民共和国教育部"
date = "2024"
content = "奖励特别优秀学生的级别最高的国家级奖学金。"

[[items]]
title = "优秀学生奖学金一等奖"
subtitle = "中山大学"
date = "2025"
content = "用于奖励德、智、体、美、劳全面发展、品学兼优的本科生。"

[[items]]
title = "优秀学生奖学金一等奖"
subtitle = "中山大学"
date = "2024"
content = "用于奖励德、智、体、美、劳全面发展、品学兼优的本科生。"

[[items]]
title = "省级一等奖，全国大学生数学建模竞赛"
subtitle = "中国工业与应用数学学会 (CSIAM)"
date = "2024"
content = "全国大学生数学建模竞赛——省级一等奖。"
