[[news]]
date = "2026-03"
content = "加入清华大学深圳国际研究生院，担任研究助理，在李伟佳老师指导下工作"

[[news]]
date = "2026-01"
content = "开始在 RUBY ZHANG PTE. LTD. 担任量化实习生"

[[news]]
date = "2025-11"
content = "我们的论文 **SatSAM2** 被 CVPR 2026 Findings 接收"

[[news]]
date = "2025-10"
content = "关于栅格建筑简化的论文发表于 *Geo-spatial Information Science*"

[[news]]
date = "2025-10"
content = "连续第二年获得国家奖学金"

[[news]]
date = "2024-10"
content = "首次获得国家奖学金"
